version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.10
    resource_class: small
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
          name: Install dependencies
      - run:
          command: pipenv run python ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
  tagged-build:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/
