# Generated by Django 2.1.11 on 2019-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityad',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityad',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
