# Generated by Django 2.0.1 on 2018-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20170729_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Individual'), (2, 'Relay segment')], default=0),
        ),
    ]
