# Generated by Django 2.0.1 on 2018-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_event_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gender',
            new_name='type',
        ),
    ]
