# Generated by Django 2.0.1 on 2018-04-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_competition_type_of_timekeeping'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='slug',
            field=models.URLField(null=True, unique=True),
            preserve_default=False,
        ),
    ]
