# Generated by Django 2.0.1 on 2018-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20180517_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayorder',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
