# Generated by Django 2.0.1 on 2018-05-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_relayorder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relayorder',
            old_name='type',
            new_name='index',
        ),
    ]
