# Generated by Django 2.0.5 on 2018-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_auto_20180527_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_concept',
            field=models.BooleanField(default=False),
        ),
    ]
