# Generated by Django 2.0.5 on 2018-06-03 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rankings', '0012_competition_is_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualresult',
            name='extra_analysis_time_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
