# Generated by Django 2.0.5 on 2018-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0014_auto_20180603_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='name',
            field=models.CharField(default="Naam", max_length=100),
            preserve_default=False,
        )
    ]
