# Generated by Django 2.0.5 on 2018-06-09 13:54

from django.db import migrations, models


def create_name(apps, schema_editor):
    Athlete = apps.get_model("rankings", "Athlete")
    for athlete in Athlete.objects.all():
        athlete.name = athlete.first_name + " " + athlete.last_name
        athlete.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_athlete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RunPython(create_name)
    ]
