# Generated by Django 2.0.5 on 2018-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0016_auto_20180609_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
    ]
