# Generated by Django 2.1.5 on 2019-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0018_auto_20180819_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_europe_cup_competition',
            field=models.BooleanField(default=False),
        ),
    ]
