# Generated by Django 2.1.5 on 2019-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0019_auto_20190406_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_points_in_athlete_total',
            field=models.BooleanField(default=False),
        ),
    ]
