# Generated by Django 2.1.5 on 2019-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0021_auto_20190406_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='imported_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
