# Generated by Django 2.1.5 on 2019-04-20 13:06

from django.db import migrations
from django.db.models import Q


def make_many_nationalities(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Athlete = apps.get_model('rankings', 'Athlete')

    for athlete in Athlete.objects.filter(~Q(nationality=None)):
        athlete.nationalities.add(athlete.nationality)


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0024_auto_20190420_1505'),
    ]

    operations = [
        migrations.RunPython(make_many_nationalities)
    ]
