# Generated by Django 2.1.5 on 2019-04-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0025_auto_20190420_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='nationality',
        ),
    ]
