# Generated by Django 2.1.5 on 2019-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0026_remove_athlete_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='is_parent_country',
            field=models.BooleanField(default=False),
        ),
    ]
