# Generated by Django 2.1.5 on 2019-04-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0027_nationality_is_parent_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='flag_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
