# Generated by Django 2.1.5 on 2019-04-21 08:34

from django.db import migrations
from django.db.models import Q


def year_of_birth_to_four_digits(apps, schema_editor):
    Athlete = apps.get_model('rankings', 'Athlete')
    current_year = 19

    for athlete in Athlete.objects.filter(~Q(year_of_birth=None)):
        if athlete.year_of_birth > current_year:
            athlete.year_of_birth = athlete.year_of_birth + 1900
        else:
            athlete.year_of_birth = athlete.year_of_birth + 2000
        athlete.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0028_auto_20190421_0946'),
    ]

    operations = [
        migrations.RunPython(year_of_birth_to_four_digits)
    ]
