# Generated by Django 2.1.5 on 2019-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0029_auto_20190421_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletes', models.ManyToManyField(to='rankings.Athlete')),
            ],
        ),
    ]
