# Generated by Django 2.1.5 on 2019-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0031_auto_20190502_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualresult',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
