# Generated by Django 2.1.5 on 2019-05-05 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0032_individualresult_round'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualresult',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='nationalities',
            field=models.ManyToManyField(blank=True, default=None, related_name='nationalities', to='rankings.Nationality'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualresult',
            name='extra_analysis_time_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
