# Generated by Django 2.1.5 on 2019-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0033_auto_20190505_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualresult',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
