# Generated by Django 2.1.5 on 2019-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0034_individualresult_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
