# Generated by Django 2.1.5 on 2019-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0035_competition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(1, 'Scheduled for import'), (2, 'Imported'), (3, 'Unable to import'), (4, 'Wanted')], default=2),
        ),
    ]
