# Generated by Django 2.1.5 on 2019-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0036_auto_20190508_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
