# Generated by Django 2.1.5 on 2019-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0037_competition_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
