# Generated by Django 2.1.5 on 2019-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0038_auto_20190508_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='imported_on',
        ),
        migrations.AddField(
            model_name='competition',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
    ]
