# Generated by Django 2.1.5 on 2019-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0039_auto_20190509_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
