# Generated by Django 2.1.5 on 2019-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0040_auto_20190509_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualresult',
            name='did_not_start',
            field=models.BooleanField(default=False),
        ),
    ]
