# Generated by Django 2.2.1 on 2019-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0041_individualresult_did_not_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-published_on']},
        ),
        migrations.AddField(
            model_name='nationality',
            name='lenex_code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
