# Generated by Django 2.2.1 on 2019-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0042_auto_20190610_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
