# Generated by Django 2.2.1 on 2019-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0043_competition_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='credit',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
