# Generated by Django 2.1.11 on 2019-08-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0044_auto_20190718_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualresult',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_results', to='rankings.Competition'),
        ),
    ]
