# Generated by Django 2.1.11 on 2019-10-26 12:59

from django.db import migrations, models
from django.utils.text import slugify


def create_event_slug(apps, schema_editor):
    Event = apps.get_model('rankings', 'Event')

    for event in Event.objects.all():
        event.slug = slugify(event.name)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0046_auto_20190824_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(null=True, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(create_event_slug),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(null=True, max_length=60, unique=True),
        ),
    ]
