# Generated by Django 3.0.5 on 2020-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0048_auto_20191203_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.IntegerField(choices=[(1, 'Scheduled for import'), (2, 'Imported'), (3, 'Unable to import'), (4, 'Wanted'), (5, 'Extra time competition')], default=2),
        ),
    ]
