# Generated by Django 3.0.5 on 2020-05-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0049_auto_20200521_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], default=0)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Competition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Event')),
            ],
        ),
    ]
