# Generated by Django 3.0.5 on 2020-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0049_auto_20200521_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualresult',
            name='time',
            field=models.DurationField(blank=True),
        ),
    ]
