# Generated by Django 3.0.5 on 2020-06-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0050_auto_20200606_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualresult',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
