# Generated by Django 3.0.5 on 2020-06-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0051_auto_20200606_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='alias_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rankings.Athlete'),
        ),
    ]
