# Generated by Django 3.0.5 on 2020-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0051_auto_20200528_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='time',
            field=models.DurationField(default='1:00.00'),
            preserve_default=False,
        ),
    ]
