# Generated by Django 3.0.7 on 2020-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0053_auto_20200607_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualresult',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
