# Generated by Django 3.0.7 on 2020-06-07 14:22
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0056_auto_20200607_1828'),
    ]

    operations = [
        TrigramExtension()
    ]
