# Generated by Django 3.0.7 on 2020-06-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0056_auto_20200607_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='SegmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Athlete')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.RelayOrder')),
            ],
        ),
        migrations.CreateModel(
            name='RelayTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_team_name', models.CharField(max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Competition')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.Team')),
            ],
        ),
        migrations.CreateModel(
            name='RelayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Event')),
                ('relay_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.RelayTeam')),
                ('segment_results', models.ManyToManyField(to='rankings.SegmentResult')),
            ],
        ),
    ]
