# Generated by Django 3.0.7 on 2020-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0056_trigram_similarity_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualresult',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
