# Generated by Django 3.0.7 on 2021-04-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0058_auto_20210124_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nationality',
            new_name='Country',
        ),
    ]
