# Generated by Django 3.0.7 on 2021-01-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0058_auto_20210124_1559'),
    ]
