# Generated by Django 3.2 on 2021-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0060_auto_20210407_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='original_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
