# Generated by Django 3.2 on 2021-04-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0060_auto_20210407_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayteam',
            name='competition',
        ),
        migrations.AddField(
            model_name='relayresult',
            name='competition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rankings.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relayresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relayresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='relayteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relayteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
