# Generated by Django 3.2.2 on 2021-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0061_auto_20210423_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='file_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
