# Generated by Django 3.2.2 on 2021-05-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0062_alter_competition_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='relayorder',
            options={'ordering': ['event', 'index']},
        ),
    ]
