# Generated by Django 3.2.3 on 2021-05-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0063_auto_20210517_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', related_query_name='videos', to='rankings.competition')),
            ],
        ),
    ]
