# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='name',
            field=models.CharField(default='hastalavista', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisgroup',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
