# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170730_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
