# Generated by Django 2.0.1 on 2018-01-14 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisgroup_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisgroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
