# Generated by Django 2.0.1 on 2018-05-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0010_auto_20180517_1144'),
        ('analysis', '0006_groupteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEventSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('athlete', models.ManyToManyField(to='rankings.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Event')),
                ('group_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.GroupTeam')),
            ],
        ),
    ]
