# Generated by Django 2.0.1 on 2018-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20180520_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupeventsetup',
            name='group_team',
        ),
        migrations.AddField(
            model_name='groupteam',
            name='setups',
            field=models.ManyToManyField(to='analysis.GroupEventSetup'),
        ),
    ]
