# Generated by Django 2.0.5 on 2018-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20180521_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='simulation_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
