# Generated by Django 3.0.5 on 2020-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_analysisgroup_simulation_date_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialResultGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('special_results', models.ManyToManyField(to='analysis.SpecialResult')),
            ],
        ),
    ]
