# Generated by Django 3.0.5 on 2020-05-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20200520_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialresult',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='specialresultgroup',
            name='special_results',
        ),
        migrations.AddField(
            model_name='specialresult',
            name='special_result_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.SpecialResultGroup'),
        ),
    ]
