# Generated by Django 3.0.5 on 2020-05-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20200521_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisgroup',
            old_name='athlete',
            new_name='athletes',
        ),
        migrations.RemoveField(
            model_name='analysisgroup',
            name='gender',
        ),
    ]
