# Generated by Django 3.0.5 on 2020-06-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20200521_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisgroup',
            options={'ordering': ('pk',)},
        ),
    ]
