# Generated by Django 3.0.7 on 2020-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_auto_20200606_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
